dist: trusty

sudo: false

os:
  - linux
  # - osx

env:
  - PACKAGE="FlowType" SUBLIME_TEXT_VERSION="3"

before_install:
  - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
  - export PATH=$HOME/.local/bin:$PATH

install:
  - sh travis.sh bootstrap
  - travis_retry pip install --upgrade pip --user `whoami`
  - travis_retry pip install -r requirements-dev.txt --user `whoami`

script:
  - sh travis.sh run_tests --coverage
  - make check

after_success:
  - travis_retry pip install codecov --user `whoami`
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change
