"""
Flow's list of built-in types available in 0.44.0 (Apr 13, 2017).

Related to
    https://flow.org/en/docs/types/
and
    http://www.saltycrane.com/blog/2016/06/flow-type-cheat-sheet/
"""


def printTypeFormat(trigger, content=None, description=None):
    """Format output for autocompletion for a given trigger text."""
    return ("%s\t%s" % (trigger, description), "%s," % (content or trigger))


builtintypes = [
    # Built-in types
    printTypeFormat("any", description="Flow built-in type"),
    printTypeFormat("boolean", description="Flow built-in type"),
    printTypeFormat("null", description="Flow built-in type"),
    printTypeFormat("number", description="Flow built-in type"),
    printTypeFormat("mixed", description="Flow built-in type"),
    printTypeFormat("string", description="Flow built-in type"),
    printTypeFormat("void", description="Flow built-in type"),
    printTypeFormat("Class", "Class<${1}>", "Flow built-in type"),

    # Built-in 'private' types
    printTypeFormat(
        "Abstract", "\$Abstract<${1}>", "Flow built-in private type"),
    printTypeFormat("Diff", "\$Diff<${1}, ${2}>",
                    "Flow built-in private type"),
    printTypeFormat("Exact", "\$Exact<${1}>", "Flow built-in private type"),
    printTypeFormat("Keys", "\$Keys<${1}>", "Flow built-in private type"),
    printTypeFormat(
        "ObjMap", "\$ObjMap<${1}, ${2}>", "Flow built-in private type"),
    printTypeFormat("PropertyType", "\$PropertyType<${1}, ${2}>",
                    "Flow built-in private type"),
    printTypeFormat(
        "Subtype", "\$Subtype<${1}, ${2}>", "Flow built-in private type"),
    printTypeFormat(
        "Supertype", "\$Supertype<${1}, ${2}>", "Flow built-in private type"),

    # Core types
    printTypeFormat("Array", "Array<${1}>", "Flow core type"),
    printTypeFormat("ArrayBuffer", description="Flow core type"),
    printTypeFormat("AsyncIterable", "AsyncIterable<${1}>", "Flow core type"),
    printTypeFormat("AsyncIterator", "AsyncIterator<${1}>", "Flow core type"),
    printTypeFormat("Boolean", description="Flow core type"),
    printTypeFormat("CallSite", description="Flow core type"),
    printTypeFormat("DataView", description="Flow core type"),
    printTypeFormat("Date", description="Flow core type"),
    printTypeFormat("Error", description="Flow core type"),
    printTypeFormat("EvalError", description="Flow core type"),
    printTypeFormat("Float32Array", description="Flow core type"),
    printTypeFormat("Float64Array", description="Flow core type"),
    printTypeFormat("Function", description="Flow core type"),
    printTypeFormat("global", description="Flow core type"),
    printTypeFormat("Infinity", description="Flow core type"),
    printTypeFormat("Int16Array", description="Flow core type"),
    printTypeFormat("Int32Array", description="Flow core type"),
    printTypeFormat("Int8Array", description="Flow core type"),
    printTypeFormat("Iterable", "Iterable<${1}>", "Flow core type"),
    printTypeFormat("Iterator", "Iterator<${1}>", "Flow core type"),
    printTypeFormat("IteratorResult", "IteratorResult<${1}, ${2}>",
                    "Flow core type"),
    printTypeFormat("JSON", description="Flow core type"),
    printTypeFormat("Map", "Map<${1}, ${2}>", "Flow core type"),
    printTypeFormat("NaN", description="Flow core type"),
    printTypeFormat("Number", description="Flow core type"),
    printTypeFormat("Object", description="Flow core type"),
    printTypeFormat("Promise", "Promise<${1}>", "Flow core type"),
    printTypeFormat("Proxy", "Proxy<${1}>", "Flow core type"),
    printTypeFormat("RangeError", description="Flow core type"),
    printTypeFormat("ReferenceError", description="Flow core type"),
    printTypeFormat("Reflect", description="Flow core type"),
    printTypeFormat("RegExp", description="Flow core type"),
    printTypeFormat("Set", "Set<${1}>", "Flow core type"),
    printTypeFormat("String", description="Flow core type"),
    printTypeFormat("Symbol", description="Flow core type"),
    printTypeFormat("SyntaxError", description="Flow core type"),
    printTypeFormat("TypeError", description="Flow core type"),
    printTypeFormat("Uint16Array", description="Flow core type"),
    printTypeFormat("Uint32Array", description="Flow core type"),
    printTypeFormat("Uint8Array", description="Flow core type"),
    printTypeFormat("Uint8ClampedArray", description="Flow core type"),
    printTypeFormat("URIError", description="Flow core type"),
    printTypeFormat("WeakMap", "WeakMap<${1}, ${2}>", "Flow core type"),
    printTypeFormat("WeakSet", "WeakSet<${1}>", "Flow core type"),

    # Core 'private' types
    printTypeFormat("ArrayBufferView", "\$ArrayBufferView",
                    description="Flow core private type"),
    printTypeFormat("ReadOnlyArray", "\$ReadOnlyArray<${1}>",
                    description="Flow core private type"),
    printTypeFormat("SymboIsConcatSpreadable", "\$SymboIsConcatSpreadable",
                    description="Flow core private type"),
    printTypeFormat("SymbolHasInstance", "\$SymbolHasInstance",
                    description="Flow core private type"),
    printTypeFormat("SymbolIterator", "\$SymbolIterator",
                    description="Flow core private type"),
    printTypeFormat("SymbolMatch", "\$SymbolMatch",
                    description="Flow core private type"),
    printTypeFormat("SymbolReplace", "\$SymbolReplace",
                    description="Flow core private type"),
    printTypeFormat("SymbolSearch", "\$SymbolSearch",
                    description="Flow core private type"),
    printTypeFormat("SymbolSpecies", "\$SymbolSpecies",
                    description="Flow core private type"),
    printTypeFormat("SymbolSplit", "\$SymbolSplit",
                    description="Flow core private type"),
    printTypeFormat("SymbolToPrimitive", "\$SymbolToPrimitive",
                    description="Flow core private type"),
    printTypeFormat("SymbolToStringTag", "\$SymbolToStringTag",
                    description="Flow core private type"),
    printTypeFormat("SymbolUnscopables", "\$SymbolUnscopables",
                    description="Flow core private type"),
    printTypeFormat("TypedArray", "\$TypedArray",
                    description="Flow core private type"),
    printTypeFormat("Proxyrevocable", "Proxy\$revocable<${1}>",
                    description="Flow core private type"),
    printTypeFormat("Proxytraps", "Proxy\$traps<${1}>",
                    description="Flow core private type"),
    printTypeFormat("RegExpflags", "RegExp\$flags",
                    description="Flow core private type"),

    # React types
    printTypeFormat("_ReactClass", "_ReactClass<${1}, ${2}, ${3}, ${4}>",
                    "Flow React type"),
    printTypeFormat("LegacyReactComponent",
                    "LegacyReactComponent<${1}, ${2}, ${3}>",
                    "Flow React type"),
    printTypeFormat("ReactClass", "ReactClass<${1}>", "Flow React type"),
    printTypeFormat("ReactPropsChainableTypeChecker",
                    description="Flow React type"),
    printTypeFormat("ReactPropsCheckType", description="Flow React type"),
    printTypeFormat("ReactPropTypes", description="Flow React type"),
    printTypeFormat("SyntheticClipboardEvent", description="Flow React type"),
    printTypeFormat("SyntheticCompositionEvent",
                    description="Flow React type"),
    printTypeFormat("SyntheticDragEvent", description="Flow React type"),
    printTypeFormat("SyntheticEvent", description="Flow React type"),
    printTypeFormat("SyntheticFocusEvent", description="Flow React type"),
    printTypeFormat("SyntheticInputEvent", description="Flow React type"),
    printTypeFormat("SyntheticKeyboardEvent", description="Flow React type"),
    printTypeFormat("SyntheticMouseEvent", description="Flow React type"),
    printTypeFormat("SyntheticTouchEvent", description="Flow React type"),
    printTypeFormat("SyntheticUIEvent", description="Flow React type"),
    printTypeFormat("SyntheticWheelEvent", description="Flow React type"),

    # React 'private' types
    printTypeFormat("DefaultPropsOf", "\$DefaultPropsOf<${1}>",
                    "Flow React type"),
    printTypeFormat("JSXIntrinsics", "\$JSXIntrinsics", "Flow React type"),
    printTypeFormat("PropsOf", "\$PropsOf<${1}>", "Flow React type"),
    printTypeFormat("ReactComponent",
                    "React\$Component<${1}, ${2}, ${3}>", "Flow React type"),
    printTypeFormat("ReactElement", "React\$Element<${1}>", "Flow React type"),
    printTypeFormat("ReactPropTypesarrayOf",
                    "React\$PropTypes\$arrayOf", "Flow React type"),
    printTypeFormat("ReactPropTypesinstanceOf",
                    "React\$PropTypes\$instanceOf", "Flow React type"),
    printTypeFormat("ReactPropTypesobjectOf",
                    "React\$PropTypes\$objectOf", "Flow React type"),
    printTypeFormat("ReactPropTypesoneOf",
                    "React\$PropTypes\$oneOf", "Flow React type"),
    printTypeFormat("ReactPropTypesoneOfType",
                    "React\$PropTypes\$oneOfType", "Flow React type"),
    printTypeFormat("ReactPropTypesshape",
                    "React\$PropTypes\$shape", "Flow React type"),
    printTypeFormat("React$PureComponent",
                    "React\$PureComponent<${1}, ${2}, ${3}>",
                    "Flow React type"),

    # Document Object Model types
    printTypeFormat("AnimationEvent", description="Flow DOM type"),
    printTypeFormat("AnimationEventHandler", description="Flow DOM type"),
    printTypeFormat("AnimationEventListener", description="Flow DOM type"),
    printTypeFormat("AnimationEventTypes", description="Flow DOM type"),
    printTypeFormat("Attr", description="Flow DOM type"),
    printTypeFormat("AudioTrack", description="Flow DOM type"),
    printTypeFormat("AudioTrackList", description="Flow DOM type"),
    printTypeFormat("Blob", description="Flow DOM type"),
    printTypeFormat("BufferDataSource", description="Flow DOM type"),
    printTypeFormat("CanvasDrawingStyles", description="Flow DOM type"),
    printTypeFormat("CanvasFillRule", description="Flow DOM type"),
    printTypeFormat("CanvasGradient", description="Flow DOM type"),
    printTypeFormat("CanvasImageSource", description="Flow DOM type"),
    printTypeFormat("CanvasPattern", description="Flow DOM type"),
    printTypeFormat("CanvasRenderingContext2D", description="Flow DOM type"),
    printTypeFormat("CharacterData", description="Flow DOM type"),
    printTypeFormat("ClientRect", description="Flow DOM type"),
    printTypeFormat("ClientRectList", description="Flow DOM type"),
    printTypeFormat("Comment", description="Flow DOM type"),
    printTypeFormat("CustomElementRegistry", description="Flow DOM type"),
    printTypeFormat("CustomEvent", description="Flow DOM type"),
    printTypeFormat("DataTransfer", description="Flow DOM type"),
    printTypeFormat("DataTransferItem", description="Flow DOM type"),
    printTypeFormat("DataTransferItemList", description="Flow DOM type"),
    printTypeFormat("Document", description="Flow DOM type"),
    printTypeFormat("DocumentFragment", description="Flow DOM type"),
    printTypeFormat("DocumentType", description="Flow DOM type"),
    printTypeFormat("DOMError", description="Flow DOM type"),
    printTypeFormat("DOMImplementation", description="Flow DOM type"),
    printTypeFormat("DOMTokenList", description="Flow DOM type"),
    printTypeFormat("DragEvent", description="Flow DOM type"),
    printTypeFormat("DragEventHandler", description="Flow DOM type"),
    printTypeFormat("DragEventListener", description="Flow DOM type"),
    printTypeFormat("DragEventTypes", description="Flow DOM type"),
    printTypeFormat("Element", description="Flow DOM type"),
    printTypeFormat("ElementRegistrationOptions", description="Flow DOM type"),
    printTypeFormat("Event", description="Flow DOM type"),
    printTypeFormat("EventHandler", description="Flow DOM type"),
    printTypeFormat("EventListener", description="Flow DOM type"),
    printTypeFormat("EventListenerOptionsOrUseCapture",
                    description="Flow DOM type"),
    printTypeFormat("EventTarget", description="Flow DOM type"),
    printTypeFormat("File", description="Flow DOM type"),
    printTypeFormat("FileList", description="Flow DOM type"),
    printTypeFormat("FileReader", description="Flow DOM type"),
    printTypeFormat("HitRegionOptions", description="Flow DOM type"),
    printTypeFormat("HTMLAnchorElement", description="Flow DOM type"),
    printTypeFormat("HTMLAppletElement", description="Flow DOM type"),
    printTypeFormat("HTMLAudioElement", description="Flow DOM type"),
    printTypeFormat("HTMLBaseElement", description="Flow DOM type"),
    printTypeFormat("HTMLButtonElement", description="Flow DOM type"),
    printTypeFormat("HTMLCanvasElement", description="Flow DOM type"),
    printTypeFormat("HTMLCollection", "HTMLCollection<${1}>", "Flow DOM type"),
    printTypeFormat("HTMLDivElement", description="Flow DOM type"),
    printTypeFormat("HTMLElement", description="Flow DOM type"),
    printTypeFormat("HTMLEmbedElement", description="Flow DOM type"),
    printTypeFormat("HTMLFormElement", description="Flow DOM type"),
    printTypeFormat("HTMLIFrameElement", description="Flow DOM type"),
    printTypeFormat("HTMLImageElement", description="Flow DOM type"),
    printTypeFormat("HTMLInputElement", description="Flow DOM type"),
    printTypeFormat("HTMLLabelElement", description="Flow DOM type"),
    printTypeFormat("HTMLLinkElement", description="Flow DOM type"),
    printTypeFormat("HTMLMediaElement", description="Flow DOM type"),
    printTypeFormat("HTMLMenuElement", description="Flow DOM type"),
    printTypeFormat("HTMLMetaElement", description="Flow DOM type"),
    printTypeFormat("HTMLOptGroupElement", description="Flow DOM type"),
    printTypeFormat("HTMLOptionElement", description="Flow DOM type"),
    printTypeFormat("HTMLOptionsCollection", description="Flow DOM type"),
    printTypeFormat("HTMLParagraphElement", description="Flow DOM type"),
    printTypeFormat("HTMLScriptElement", description="Flow DOM type"),
    printTypeFormat("HTMLSelectElement", description="Flow DOM type"),
    printTypeFormat("HTMLSlotElement", description="Flow DOM type"),
    printTypeFormat("HTMLSourceElement", description="Flow DOM type"),
    printTypeFormat("HTMLSpanElement", description="Flow DOM type"),
    printTypeFormat("HTMLStyleElement", description="Flow DOM type"),
    printTypeFormat("HTMLTableCaptionElement", description="Flow DOM type"),
    printTypeFormat("HTMLTableCellElement", description="Flow DOM type"),
    printTypeFormat("HTMLTableElement", description="Flow DOM type"),
    printTypeFormat("HTMLTableRowElement", description="Flow DOM type"),
    printTypeFormat("HTMLTableSectionElement", description="Flow DOM type"),
    printTypeFormat("HTMLTemplateElement", description="Flow DOM type"),
    printTypeFormat("HTMLTextAreaElement", description="Flow DOM type"),
    printTypeFormat("HTMLVideoElement", description="Flow DOM type"),
    printTypeFormat("Image", description="Flow DOM type"),
    printTypeFormat("ImageBitmap", description="Flow DOM type"),
    printTypeFormat("ImageData", description="Flow DOM type"),
    printTypeFormat("KeyboardEvent", description="Flow DOM type"),
    printTypeFormat("KeyboardEventHandler", description="Flow DOM type"),
    printTypeFormat("KeyboardEventListener", description="Flow DOM type"),
    printTypeFormat("KeyboardEventTypes", description="Flow DOM type"),
    printTypeFormat("MediaError", description="Flow DOM type"),
    printTypeFormat("MediaSource", description="Flow DOM type"),
    printTypeFormat("MessageEvent", description="Flow DOM type"),
    printTypeFormat("MouseEvent", description="Flow DOM type"),
    printTypeFormat("MouseEventHandler", description="Flow DOM type"),
    printTypeFormat("MouseEventListener", description="Flow DOM type"),
    printTypeFormat("MouseEventTypes", description="Flow DOM type"),
    printTypeFormat("NamedNodeMap", description="Flow DOM type"),
    printTypeFormat("Node", description="Flow DOM type"),
    printTypeFormat("NodeFilter", description="Flow DOM type"),
    printTypeFormat("NodeFilterCallback", description="Flow DOM type"),
    printTypeFormat("NodeFilterInterface", description="Flow DOM type"),
    printTypeFormat("NodeIterator", "NodeIterator<${1}, ${2}>",
                    "Flow DOM type"),
    printTypeFormat("NodeList", "NodeList<${1}>", "Flow DOM type"),
    printTypeFormat("Path2D", description="Flow DOM type"),
    printTypeFormat("ProgressEvent", description="Flow DOM type"),
    printTypeFormat("ProgressEventHandler", description="Flow DOM type"),
    printTypeFormat("ProgressEventListener", description="Flow DOM type"),
    printTypeFormat("ProgressEventTypes", description="Flow DOM type"),
    printTypeFormat("PromiseRejectionEvent", description="Flow DOM type"),
    printTypeFormat("Range", description="Flow DOM type"),
    printTypeFormat("RenderingContext", description="Flow DOM type"),
    printTypeFormat("Selection", description="Flow DOM type"),
    printTypeFormat("SelectionDirection", description="Flow DOM type"),
    printTypeFormat("SelectionMode", description="Flow DOM type"),
    printTypeFormat("ShadowRoot", description="Flow DOM type"),
    printTypeFormat("SourceBuffer", description="Flow DOM type"),
    printTypeFormat("SourceBufferList", description="Flow DOM type"),
    printTypeFormat("Storage", description="Flow DOM type"),
    printTypeFormat("SVGMatrix", description="Flow DOM type"),
    printTypeFormat("TexImageSource", description="Flow DOM type"),
    printTypeFormat("Text", description="Flow DOM type"),
    printTypeFormat("TextMetrics", description="Flow DOM type"),
    printTypeFormat("TextRange", description="Flow DOM type"),
    printTypeFormat("TextTrack", description="Flow DOM type"),
    printTypeFormat("TextTrackCue", description="Flow DOM type"),
    printTypeFormat("TextTrackCueList", description="Flow DOM type"),
    printTypeFormat("TextTrackList", description="Flow DOM type"),
    printTypeFormat("TimeRanges", description="Flow DOM type"),
    printTypeFormat("Touch", description="Flow DOM type"),
    printTypeFormat("TouchEvent", description="Flow DOM type"),
    printTypeFormat("TouchEventHandler", description="Flow DOM type"),
    printTypeFormat("TouchEventListener", description="Flow DOM type"),
    printTypeFormat("TouchEventTypes", description="Flow DOM type"),
    printTypeFormat("TouchList", description="Flow DOM type"),
    printTypeFormat("TrackDefault", description="Flow DOM type"),
    printTypeFormat("TrackDefaultList", description="Flow DOM type"),
    printTypeFormat("TreeWalker", "TreeWalker<${1}, ${2}>", "Flow DOM type"),
    printTypeFormat("UIEvent", description="Flow DOM type"),
    printTypeFormat("URL", description="Flow DOM type"),
    printTypeFormat("ValidityState", description="Flow DOM type"),
    printTypeFormat("VertexAttribFVSource", description="Flow DOM type"),
    printTypeFormat("VideoTrack", description="Flow DOM type"),
    printTypeFormat("VideoTrackList", description="Flow DOM type"),
    printTypeFormat("WebGLContextAttributes", description="Flow DOM type"),
    printTypeFormat("WebGLContextEvent", description="Flow DOM type"),
    printTypeFormat("WebGLRenderingContext", description="Flow DOM type"),
    printTypeFormat("WheelEvent", description="Flow DOM type"),
    printTypeFormat("WheelEventHandler", description="Flow DOM type"),
    printTypeFormat("WheelEventListener", description="Flow DOM type"),
    printTypeFormat("WheelEventTypes", description="Flow DOM type"),

    # Document Object Model 'private' types
    printTypeFormat("CustomEventInit", "CustomEvent\$Init",
                    "Flow DOM private type"),
    printTypeFormat("EventInit", "Event\$Init", "Flow DOM private type"),

    # Browser Object Model types
    printTypeFormat("AnalyserNode", description="Flow BOM type"),
    printTypeFormat("AudioBuffer", description="Flow BOM type"),
    printTypeFormat("AudioBufferSourceNode", description="Flow BOM type"),
    printTypeFormat("AudioContext", description="Flow BOM type"),
    printTypeFormat("AudioDestinationNode", description="Flow BOM type"),
    printTypeFormat("AudioListener", description="Flow BOM type"),
    printTypeFormat("AudioNode", description="Flow BOM type"),
    printTypeFormat("AudioParam", description="Flow BOM type"),
    printTypeFormat("BatteryManager", description="Flow BOM type"),
    printTypeFormat("BiquadFilterNode", description="Flow BOM type"),
    printTypeFormat("BodyInit", description="Flow BOM type"),
    printTypeFormat("CacheType", description="Flow BOM type"),
    printTypeFormat("ChannelMergerNode", description="Flow BOM type"),
    printTypeFormat("ChannelSplitterNode", description="Flow BOM type"),
    printTypeFormat("CloseEvent", description="Flow BOM type"),
    printTypeFormat("ConvolverNode", description="Flow BOM type"),
    printTypeFormat("Coordinates", description="Flow BOM type"),
    printTypeFormat("CredentialsType", description="Flow BOM type"),
    printTypeFormat("DedicatedWorkerGlobalScope", description="Flow BOM type"),
    printTypeFormat("DelayNode", description="Flow BOM type"),
    printTypeFormat("DOMParser", description="Flow BOM type"),
    printTypeFormat("DynamicsCompressorNode", description="Flow BOM type"),
    printTypeFormat("FormData", description="Flow BOM type"),
    printTypeFormat("FormDataEntryValue", description="Flow BOM type"),
    printTypeFormat("GainNode", description="Flow BOM type"),
    printTypeFormat("Gamepad", description="Flow BOM type"),
    printTypeFormat("GamepadButton", description="Flow BOM type"),
    printTypeFormat("Geolocation", description="Flow BOM type"),
    printTypeFormat("Headers", description="Flow BOM type"),
    printTypeFormat("HeadersInit", description="Flow BOM type"),
    printTypeFormat("History", description="Flow BOM type"),
    printTypeFormat("Location", description="Flow BOM type"),
    printTypeFormat("MediaElementAudioSourceNode",
                    description="Flow BOM type"),
    printTypeFormat("MediaStream", description="Flow BOM type"),
    printTypeFormat("MediaStreamAudioSourceNode", description="Flow BOM type"),
    printTypeFormat("MediaStreamTrack", description="Flow BOM type"),
    printTypeFormat("MessageChannel", description="Flow BOM type"),
    printTypeFormat("MessagePort", description="Flow BOM type"),
    printTypeFormat("MethodType", description="Flow BOM type"),
    printTypeFormat("MimeType", description="Flow BOM type"),
    printTypeFormat("MimeTypeArray", description="Flow BOM type"),
    printTypeFormat("ModeType", description="Flow BOM type"),
    printTypeFormat("MutationObserver", description="Flow BOM type"),
    printTypeFormat("MutationObserverInitRequired",
                    description="Flow BOM type"),
    printTypeFormat("MutationRecord", description="Flow BOM type"),
    printTypeFormat("Navigator", description="Flow BOM type"),
    printTypeFormat("NavigatorCommon", description="Flow BOM type"),
    printTypeFormat("OscillatorNode", description="Flow BOM type"),
    printTypeFormat("PannerNode", description="Flow BOM type"),
    printTypeFormat("Performance", description="Flow BOM type"),
    printTypeFormat("PerformanceEntry", description="Flow BOM type"),
    printTypeFormat("PerformanceEntryFilterOptions",
                    description="Flow BOM type"),
    printTypeFormat("PerformanceNavigation", description="Flow BOM type"),
    printTypeFormat("PerformanceNavigationTiming",
                    description="Flow BOM type"),
    printTypeFormat("PerformanceResourceTiming", description="Flow BOM type"),
    printTypeFormat("PerformanceTiming", description="Flow BOM type"),
    printTypeFormat("PeriodicWave", description="Flow BOM type"),
    printTypeFormat("Plugin", description="Flow BOM type"),
    printTypeFormat("PluginArray", description="Flow BOM type"),
    printTypeFormat("Position", description="Flow BOM type"),
    printTypeFormat("PositionError", description="Flow BOM type"),
    printTypeFormat("PositionOptions", description="Flow BOM type"),
    printTypeFormat("RedirectType", description="Flow BOM type"),
    printTypeFormat("ReferrerPolicyType", description="Flow BOM type"),
    printTypeFormat("Request", description="Flow BOM type"),
    printTypeFormat("RequestOptions", description="Flow BOM type"),
    printTypeFormat("Response", description="Flow BOM type"),
    printTypeFormat("ResponseOptions", description="Flow BOM type"),
    printTypeFormat("ResponseType", description="Flow BOM type"),
    printTypeFormat("Screen", description="Flow BOM type"),
    printTypeFormat("ScriptProcessorNode", description="Flow BOM type"),
    printTypeFormat("SharedWorker", description="Flow BOM type"),
    printTypeFormat("SharedWorkerGlobalScope", description="Flow BOM type"),
    printTypeFormat("TextDecoder", description="Flow BOM type"),
    printTypeFormat("TextEncoder", description="Flow BOM type"),
    printTypeFormat("URLSearchParams", description="Flow BOM type"),
    printTypeFormat("WaveShaperNode", description="Flow BOM type"),
    printTypeFormat("WebSocket", description="Flow BOM type"),
    printTypeFormat("Worker", description="Flow BOM type"),
    printTypeFormat("WorkerGlobalScope", description="Flow BOM type"),
    printTypeFormat("WorkerLocation", description="Flow BOM type"),
    printTypeFormat("WorkerNavigator", description="Flow BOM type"),
    printTypeFormat("XDomainRequest", description="Flow BOM type"),
    printTypeFormat("XMLHttpRequest", description="Flow BOM type"),
    printTypeFormat("XMLHttpRequestEventTarget", description="Flow BOM type"),
    printTypeFormat("XMLSerializer", description="Flow BOM type"),

    # Browser Object Model 'private' types
    printTypeFormat("TextDecoderavailableEncodings",
                    "TextDecoder\$availableEncodings",
                    "Flow BOM private type"),
    printTypeFormat("TextEncoderavailableEncodings",
                    "TextEncoder\$availableEncodings",
                    "Flow BOM private type"),

    # CSS Object Model types
    printTypeFormat("CSSRule", description="Flow CSSOM type"),
    printTypeFormat("CSSRuleList", description="Flow CSSOM type"),
    printTypeFormat("CSSStyleDeclaration", description="Flow CSSOM type"),
    printTypeFormat("CSSStyleSheet", description="Flow CSSOM type"),
    printTypeFormat("MediaList", description="Flow CSSOM type"),
    printTypeFormat("StyleSheet", description="Flow CSSOM type"),
    printTypeFormat("StyleSheetList", description="Flow CSSOM type"),
    printTypeFormat("TransitionEvent", description="Flow CSSOM type"),

    # indexedDB types
    printTypeFormat("IDBCursor", description="Flow indexedDB type"),
    printTypeFormat("IDBCursorWithValue", description="Flow indexedDB type"),
    printTypeFormat("IDBDatabase", description="Flow indexedDB type"),
    printTypeFormat("IDBDirection", description="Flow indexedDB type"),
    printTypeFormat("IDBEnvironment", description="Flow indexedDB type"),
    printTypeFormat("IDBFactory", description="Flow indexedDB type"),
    printTypeFormat("IDBIndex", description="Flow indexedDB type"),
    printTypeFormat("IDBKeyRange", description="Flow indexedDB type"),
    printTypeFormat("IDBObjectStore", description="Flow indexedDB type"),
    printTypeFormat("IDBOpenDBRequest", description="Flow indexedDB type"),
    printTypeFormat("IDBRequest", description="Flow indexedDB type"),
    printTypeFormat("IDBTransaction", description="Flow indexedDB type"),

    # Node.js types
    printTypeFormat("AssertionError", description="Flow Node.js type"),
    printTypeFormat("Buffer", description="Flow Node.js type"),
    printTypeFormat("Sign", description="Flow Node.js type"),
    printTypeFormat("Verify", description="Flow Node.js type"),
    printTypeFormat("duplexStreamOptions", description="Flow Node.js type"),
    printTypeFormat("EventEmitter", description="Flow Node.js type"),
    printTypeFormat("FSWatcher", description="Flow Node.js type"),
    printTypeFormat("ReadStream", description="Flow Node.js type"),
    printTypeFormat("Stats", description="Flow Node.js type"),
    printTypeFormat("WriteStream", description="Flow Node.js type"),
    printTypeFormat("ClientRequest", description="Flow Node.js type"),
    printTypeFormat("IncomingMessage", description="Flow Node.js type"),
    printTypeFormat("Server", description="Flow Node.js type"),
    printTypeFormat("ServerResponse", description="Flow Node.js type"),
    printTypeFormat("ClientRequest", description="Flow Node.js type"),
    printTypeFormat("IncomingMessage", description="Flow Node.js type"),
    printTypeFormat("Server", description="Flow Node.js type"),
    printTypeFormat("ServerResponse", description="Flow Node.js type"),
    printTypeFormat("Server", description="Flow Node.js type"),
    printTypeFormat("Socket", description="Flow Node.js type"),
    printTypeFormat("Process", description="Flow Node.js type"),
    printTypeFormat("readableStreamOptions", description="Flow Node.js type"),
    printTypeFormat("writableStreamOptions", description="Flow Node.js type"),
    printTypeFormat("Deflate", description="Flow Node.js type"),
    printTypeFormat("DeflateRaw", description="Flow Node.js type"),
    printTypeFormat("Gunzip", description="Flow Node.js type"),
    printTypeFormat("Gzip", description="Flow Node.js type"),
    printTypeFormat("Inflate", description="Flow Node.js type"),
    printTypeFormat("InflateRaw", description="Flow Node.js type"),
    printTypeFormat("Unzip", description="Flow Node.js type"),
    printTypeFormat("Zlib", description="Flow Node.js type"),

    # Node.js private types
    printTypeFormat("bufferEncoding", "buffer\$Encoding",
                    "Flow Node.js private type"),
    printTypeFormat("bufferNonBufferEncoding", "buffer\$NonBufferEncoding",
                    "Flow Node.js private type"),
    printTypeFormat("bufferToJSONRet", "buffer\$ToJSONRet",
                    "Flow Node.js private type"),
    printTypeFormat("child_processChildProcess",
                    "child_process\$ChildProcess",
                    "Flow Node.js private type"),
    printTypeFormat("child_processError", "child_process\$Error",
                    "Flow Node.js private type"),
    printTypeFormat("child_processexecCallback",
                    "child_process\$execCallback",
                    "Flow Node.js private type"),
    printTypeFormat("child_processexecFileCallback",
                    "child_process\$execFileCallback",
                    "Flow Node.js private type"),
    printTypeFormat("child_processexecFileOpts",
                    "child_process\$execFileOpts",
                    "Flow Node.js private type"),
    printTypeFormat("child_processexecFileSyncOpts",
                    "child_process\$execFileSyncOpts",
                    "Flow Node.js private type"),
    printTypeFormat("child_processexecOpts", "child_process\$execOpts",
                    "Flow Node.js private type"),
    printTypeFormat("child_processexecSyncOpts",
                    "child_process\$execSyncOpts",
                    "Flow Node.js private type"),
    printTypeFormat("child_processforkOpts", "child_process\$forkOpts",
                    "Flow Node.js private type"),
    printTypeFormat("child_processHandle", "child_process\$Handle",
                    "Flow Node.js private type"),
    printTypeFormat("child_processspawnOpts", "child_process\$spawnOpts",
                    "Flow Node.js private type"),
    printTypeFormat("child_processspawnRet", "child_process\$spawnRet",
                    "Flow Node.js private type"),
    printTypeFormat("child_processspawnSyncOpts",
                    "child_process\$spawnSyncOpts",
                    "Flow Node.js private type"),
    printTypeFormat("child_processspawnSyncRet",
                    "child_process\$spawnSyncRet",
                    "Flow Node.js private type"),
    printTypeFormat("clustersetupMasterOpts", "cluster\$setupMasterOpts",
                    "Flow Node.js private type"),
    printTypeFormat("clusterWorker", "cluster\$Worker",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoCipher", "crypto\$Cipher",
                    "Flow Node.js private type"),
    printTypeFormat("cryptocreateCredentialsDetails",
                    "crypto\$createCredentialsDetails",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoCredentials", "crypto\$Credentials",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoDecipher", "crypto\$Decipher",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoDiffieHellman", "crypto\$DiffieHellman",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoHash", "crypto\$Hash",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoHmac", "crypto\$Hmac",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoSign", "crypto\$Sign",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoSignprivate_key", "crypto\$Sign\$private_key",
                    "Flow Node.js private type"),
    printTypeFormat("cryptoVerify", "crypto\$Verify",
                    "Flow Node.js private type"),
    printTypeFormat("dgramSocket", "dgram\$Socket",
                    "Flow Node.js private type"),
    printTypeFormat("domainDomain", "domain\$Domain",
                    "Flow Node.js private type"),
    printTypeFormat("eventsEventEmitter", "events\$EventEmitter",
                    "Flow Node.js private type"),
    printTypeFormat("httpClientRequest", "http\$ClientRequest",
                    "Flow Node.js private type"),
    printTypeFormat("httpIncomingMessage", "http\$IncomingMessage",
                    "Flow Node.js private type"),
    printTypeFormat("httpServerResponse", "http\$ServerResponse",
                    "Flow Node.js private type"),
    printTypeFormat("netconnectOptions", "net\$connectOptions",
                    "Flow Node.js private type"),
    printTypeFormat("netServer", "net\$Server",
                    "Flow Node.js private type"),
    printTypeFormat("netSocket", "net\$Socket",
                    "Flow Node.js private type"),
    printTypeFormat("netSocketaddress", "net\$Socket\$address",
                    "Flow Node.js private type"),
    printTypeFormat("osCPU", "os\$CPU",
                    "Flow Node.js private type"),
    printTypeFormat("osNetIFAddr", "os\$NetIFAddr",
                    "Flow Node.js private type"),
    printTypeFormat("osUserInfobuffer", "os\$UserInfo\$buffer",
                    "Flow Node.js private type"),
    printTypeFormat("osUserInfostring", "os\$UserInfo\$string",
                    "Flow Node.js private type"),
    printTypeFormat("readlineInterface", "readline\$Interface",
                    "Flow Node.js private type"),
    printTypeFormat("streamDuplex", "stream\$Duplex",
                    "Flow Node.js private type"),
    printTypeFormat("streamPassThrough", "stream\$PassThrough",
                    "Flow Node.js private type"),
    printTypeFormat("streamReadable", "stream\$Readable",
                    "Flow Node.js private type"),
    printTypeFormat("streamStream", "stream\$Stream",
                    "Flow Node.js private type"),
    printTypeFormat("streamTransform", "stream\$Transform",
                    "Flow Node.js private type"),
    printTypeFormat("streamWritable", "stream\$Writable",
                    "Flow Node.js private type"),
    printTypeFormat("string_decoderStringDecoder",
                    "string_decoder\$StringDecoder",
                    "Flow Node.js private type"),
    printTypeFormat("tlsServer", "tls\$Server",
                    "Flow Node.js private type"),
    printTypeFormat("tlsTLSSocket", "tls\$TLSSocket",
                    "Flow Node.js private type"),
    printTypeFormat("ttyReadStream", "tty\$ReadStream",
                    "Flow Node.js private type"),
    printTypeFormat("ttyWriteStream", "tty\$WriteStream",
                    "Flow Node.js private type"),
    printTypeFormat("vmContext", "vm\$Context",
                    "Flow Node.js private type"),
    printTypeFormat("vmScript", "vm\$Script",
                    "Flow Node.js private type"),
    printTypeFormat("vmScriptOptions", "vm\$ScriptOptions",
                    "Flow Node.js private type"),
    printTypeFormat("zlibasyncFn", "zlib\$asyncFn",
                    "Flow Node.js private type"),
    printTypeFormat("zliboptions", "zlib\$options",
                    "Flow Node.js private type"),
    printTypeFormat("zlibsyncFn", "zlib\$syncFn",
                    "Flow Node.js private type"),

    # Service Workers types
    printTypeFormat("Cache", description="Flow service worker type"),
    printTypeFormat("CacheQueryOptions",
                    description="Flow service worker type"),
    printTypeFormat("CacheStorage", description="Flow service worker type"),
    printTypeFormat("Client", description="Flow service worker type"),
    printTypeFormat("ClientQueryOptions",
                    description="Flow service worker type"),
    printTypeFormat("Clients", description="Flow service worker type"),
    printTypeFormat("ClientType", description="Flow service worker type"),
    printTypeFormat("ExtendableEvent", description="Flow service worker type"),
    printTypeFormat("FetchEvent", description="Flow service worker type"),
    printTypeFormat("ForeignFetchOptions",
                    description="Flow service worker type"),
    printTypeFormat("FrameType", description="Flow service worker type"),
    printTypeFormat("InstallEvent", description="Flow service worker type"),
    printTypeFormat("NavigationPreloadManager",
                    description="Flow service worker type"),
    printTypeFormat("NavigationPreloadState",
                    description="Flow service worker type"),
    printTypeFormat("RegistrationOptions",
                    description="Flow service worker type"),
    printTypeFormat("RequestInfo", description="Flow service worker type"),
    printTypeFormat("ServiceWorker", description="Flow service worker type"),
    printTypeFormat("ServiceWorkerContainer",
                    description="Flow service worker type"),
    printTypeFormat("ServiceWorkerMessageEvent",
                    description="Flow service worker type"),
    printTypeFormat("ServiceWorkerRegistration",
                    description="Flow service worker type"),
    printTypeFormat("ServiceWorkerState",
                    description="Flow service worker type"),
    printTypeFormat("VisibilityState", description="Flow service worker type"),
    printTypeFormat("WindowClient", description="Flow service worker type"),
    printTypeFormat("WorkerType", description="Flow service worker type"),

    # Streams types
    printTypeFormat("PipeToOptions", description="Flow streams type"),
    printTypeFormat("QueuingStrategy", description="Flow streams type"),
    printTypeFormat("ReadableByteStreamController",
                    description="Flow streams type"),
    printTypeFormat("ReadableStream", description="Flow streams type"),
    printTypeFormat("ReadableStreamBYOBRequest",
                    description="Flow streams type"),
    printTypeFormat("ReadableStreamController",
                    description="Flow streams type"),
    printTypeFormat("ReadableStreamReader", description="Flow streams type"),
    printTypeFormat("TextEncodeOptions", description="Flow streams type"),
    printTypeFormat("TextEncoder", description="Flow streams type"),
    printTypeFormat("TransformStream", description="Flow streams type"),
    printTypeFormat("UnderlyingSink", description="Flow streams type"),
    printTypeFormat("UnderlyingSource", description="Flow streams type"),
    printTypeFormat("WritableStream", description="Flow streams type"),
    printTypeFormat("WritableStreamController",
                    description="Flow streams type"),
    printTypeFormat("WritableStreamWriter", description="Flow streams type"),
]
